### ISSUE TITLE
Server crash, NPE on TileEntityDecomposer

### ISSUE THREAD

**Issue by Bourne-ID** [AdlyTempleton/MineChem#174]
TileEntityDecomposer line 265, NullPointerException experienced when decompiling a item that had no recipe (I believe it was a cookie out of all things...)

Issue appears to relate around variable recipe, the code L265/266:

```
ArrayList<Chemical> output = recipe.getOutput();
        if (recipe != null && output != null) {
```

The check to see if recipe is null is called after a method from recipe is called. Without looking deeper into the code, I assume a nested if statement will be required to check if receipe is null, and then check if output is null. 

I'll possibly make a fork/pull request for this, but my availability & github knowledge is limited. 

Stacktrace:

2014-04-29 23:02:12 [SEVERE] net.minecraft.util.ReportedException: Ticking tile entity
2014-04-29 23:02:12 [SEVERE]    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:889)
2014-04-29 23:02:12 [SEVERE]    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
2014-04-29 23:02:12 [SEVERE]    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777)
2014-04-29 23:02:12 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
2014-04-29 23:02:12 [SEVERE]    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
2014-04-29 23:02:12 [SEVERE] Caused by: java.lang.NullPointerException
2014-04-29 23:02:12 [SEVERE]    at pixlepix.minechem.common.tileentity.TileEntityDecomposer.decomposeActiveStack(TileEntityDecomposer.java:265)
2014-04-29 23:02:12 [SEVERE]    at pixlepix.minechem.common.tileentity.TileEntityDecomposer.func_70316_g(TileEntityDecomposer.java:193)
2014-04-29 23:02:12 [SEVERE]    at net.minecraft.world.World.func_72939_s(World.java:2782)
2014-04-29 23:02:12 [SEVERE]    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:883)
2014-04-29 23:02:12 [SEVERE]    ... 4 more
2014-04-29 23:02:12 [SEVERE] Encountered an unexpected exception ReportedException
net.minecraft.util.ReportedException: Ticking tile entity
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:889)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.NullPointerException
    at pixlepix.minechem.common.tileentity.TileEntityDecomposer.decomposeActiveStack(TileEntityDecomposer.java:265)
    at pixlepix.minechem.common.tileentity.TileEntityDecomposer.func_70316_g(TileEntityDecomposer.java:193)
    at net.minecraft.world.World.func_72939_s(World.java:2782)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:883)
    ... 4 more

**Comment by Bourne-ID** [comment]
Duplicate of #166. Apologies.
