### ISSUE TITLE
Blueprint Projector crash when trying to connect to another Blueprint projector

### ISSUE THREAD

**Issue by YPetremann** [AdlyTempleton/MineChem#205]
Here the crash :

2014-06-13 20:22:51 [Infos] [STDOUT] java.lang.AbstractMethodError: minechem.tileentity.blueprintprojector.BlueprintProjectorTileEntity.canConnect(Lnet/minecraftforge/common/ForgeDirection;)Z
2014-06-13 20:22:51 [Infos] [STDOUT]    at universalelectricity.core.asm.template.tile.StaticTileForwarder.canConnect(StaticTileForwarder.java:103)
2014-06-13 20:22:51 [Infos] [STDOUT]    at minechem.tileentity.prefab.MinechemTileEntity.acceptsEnergyFrom(MinechemTileEntity.java:65)
2014-06-13 20:22:51 [Infos] [STDOUT]    at ic2.core.energy.EnergyNetLocal.addTileToGrids(EnergyNetLocal.java:331)
2014-06-13 20:22:51 [Infos] [STDOUT]    at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:119)
2014-06-13 20:22:51 [Infos] [STDOUT]    at ic2.core.energy.EventHandler.onEnergyTileLoad(EventHandler.java:26)
2014-06-13 20:22:51 [Infos] [STDOUT]    at net.minecraftforge.event.ASMEventHandler_44_EventHandler_onEnergyTileLoad_EnergyTileLoadEvent.invoke(.dynamic)
2014-06-13 20:22:51 [Infos] [STDOUT]    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
2014-06-13 20:22:51 [Infos] [STDOUT]    at net.minecraftforge.event.EventBus.post(EventBus.java:108)
2014-06-13 20:22:51 [Infos] [STDOUT]    at universalelectricity.core.net.NetworkTickHandler.tickEnd(NetworkTickHandler.java:106)
2014-06-13 20:22:51 [Infos] [STDOUT]    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
2014-06-13 20:22:51 [Infos] [STDOUT]    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)
2014-06-13 20:22:51 [Infos] [STDOUT]    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:274)
2014-06-13 20:22:51 [Infos] [STDOUT]    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:622)
2014-06-13 20:22:51 [Infos] [STDOUT]    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
2014-06-13 20:22:51 [Infos] [STDOUT]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
2014-06-13 20:22:51 [Infos] [STDOUT]    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)

**Comment by jakimfett** [comment]
What do you mean by "connect to another blueprint projector"? Do you mean place them down next to eachother? Do you mean place them so their ghost blocks overlap? Do you mean connect them with buildcraft/thermalexpansion item pipes? Please be specific.

**Comment by jakimfett** [comment]
@YPetremann could I get you to provide more information, please? To be able to troubleshoot this, I need all the info specified in the "[Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting#basic-requirements)" from the Wiki.

**Comment by jakimfett** [comment]
@YPetremann if this is still effecting you, please [open a new ticket](https://github.com/pixlepix/MineChem/issues/new) and follow the "[Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting#basic-requirements)"
