### ISSUE TITLE
Trying to Decompose Repeaters crashes Game and corrupts save file.

### ISSUE THREAD

**Issue by birdwing** [AdlyTempleton/MineChem#208]
We are running version 5.0.4 of this mod on a server.
One of the players put a repeater in the decomposer and it crashed the server and corrupted the save file. I restored the save from a backup.

Included below is the crash report.

```
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 6/24/14 9:57 PM
Description: Ticking tile entity

java.lang.NullPointerException
    at pixlepix.minechem.common.tileentity.TileEntityDecomposer.decomposeActiveStack(TileEntityDecomposer.java:265)
    at pixlepix.minechem.common.tileentity.TileEntityDecomposer.func_70316_g(TileEntityDecomposer.java:193)
    at net.minecraft.world.World.func_72939_s(World.java:2209)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:550)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:276)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at pixlepix.minechem.common.tileentity.TileEntityDecomposer.decomposeActiveStack(TileEntityDecomposer.java:265)
    at pixlepix.minechem.common.tileentity.TileEntityDecomposer.func_70316_g(TileEntityDecomposer.java:193)

-- Tile entity being ticked --
Details:
    Name: minechem.tileEntityDecomposer // pixlepix.minechem.common.tileentity.TileEntityDecomposer
    Block type: ID #4013 (tile.blockChemicalDecomposer // pixlepix.minechem.common.blocks.BlockDecomposer)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-628,65,713), Chunk: (at 12,4,9 in -40,44; contains blocks -640,0,704 to -625,255,719), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
    Actual block type: ID #4013 (tile.blockChemicalDecomposer // pixlepix.minechem.common.blocks.BlockDecomposer)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2209)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:550)

-- Affected level --
Details:
    Level name: world
    All players: 0 total; []
    Chunk stats: ServerChunkCache: 653 Drop: 0
    Level seed: -7223557746051307508
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-269,64,237), Chunk: (at 3,4,13 in -17,14; contains blocks -272,0,224 to -257,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 78293694 game time, 5161643 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 53903 (now: false), thunder time: 80508 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:276)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Mac OS X (x86_64) version 10.9.3
    Java Version: 1.7.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 218383520 bytes (208 MB) / 481820672 bytes (459 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 1 total; -Xmx4G
    AABB Pool Size: 1139 (63784 bytes; 0 MB) allocated, 1037 (58072 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 20, tcache: 0, allocated: 2, tallocated: 64
    FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 82 mods loaded, 82 mods active
    mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{6.4.49.965} [Forge Mod Loader] (server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{9.11.1.965} [Minecraft Forge] (server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{0.9.0.9} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    InfiniBows{1.2.0 build 14} [Infinity Bow Fix] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PowerCrystalsCore{1.1.8} [PowerCrystals Core] (PowerCrystalsCore-1.1.8-9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct-Preloader{0.0.1} [Tinkers Corestruct] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppliedEnergistics-Core{rv14.finale3} [AppliedEnergistics Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    denLib{3.2.6} [denLib] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FEPreLoader{1.3rc1} [Forge Essentials|PreLoader] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenModsCore{@VERSION@} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DenEvents{1.0} [DenEvents] (DenEvents.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppliedEnergistics{rv14.finale3} [Applied Energistics] (appeng-rv14-finale3-mc16x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArchimedesShipsMod{1.6.4 v1.4.5} [Archimedes' Ships] (ArchimedesShips.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Autoutils{1.0.1} [Autoutils] (autoutils-1.6.4-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    barrels{3.4.1} [The Barrels Mod] (Barrels 3.4.2 - 1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.5.5} [BiblioCraft] (BiblioCraft[v1.5.5].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{4.2.2} [BuildCraft] (buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{4.2.2} [BC Builders] (buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{4.2.2} [BC Energy] (buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{4.2.2} [BC Factory] (buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{4.2.2} [BC Transport] (buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{4.2.2} [BC Silicon] (buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CarpentersBlocks{2.1.0} [Carpenter's Blocks] (Carpenter's Blocks v2.1.0 - MC 1.6+.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ChickenChunks{1.3.3.4} [ChickenChunks] (ChickenChunks 1.3.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Chisel{1.5.0} [Chisel] (chisel-1.6.4-1.5.0fix.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{2.0.0.5} [CoFH Core] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHLoot{2.0.0.5} [CoFH Loot] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHMasquerade{2.0.0.5} [CoFH Masquerade] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHSocial{2.0.0.5} [CoFH Social] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHWorld{2.0.0.5} [CoFH World] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ComputerCraft{1.63} [ComputerCraft] (ComputerCraft1.63.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CreeperCollateral{3.0.3} [CreeperCollateral] (CreeperCollateral-1.6.4-3.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderStorage{1.4.3.6} [EnderStorage] (EnderStorage 1.4.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtrabiomesXL{3.15.8} [ExtrabiomesXL] (ExtrabiomesXL-universal-1.6.4-3.15.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeEssentials{1.3rc1} [Forge Essentials] (forgeessentials-1.3rc1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Hats{2.1.8} [Hats] (Hats2.1.8.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{5.4.1.702} [Iron Chest] (ironchest-universal-1.6.4-5.4.1.702.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    minechem{5.0.3} [MineChem] (Minechem-5.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    minechem-particlephysics{5.0.3} [Minechem-Particle Physics] (Minechem-5.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MFR Compat Forestry Trees{1.0} [MFR Compat Forestry Trees] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MFR Compat Extra Trees{1.0} [MFR Compat Extra Trees] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded{1.6.4R2.7.9} [MineFactory Reloaded] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatAppliedEnergistics{1.6.4R2.7.9} [MFR Compat: Applied Energistics] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatAtum{1.6.4R2.7.9} [MFR Compat: Atum] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatBackTools{1.6.4R2.7.9} [MFR Compat: BackTools] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatBuildCraft{1.6.4R2.7.9} [MFR Compat: BuildCraft] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatChococraft{1.6.4R2.7.9} [MFR Compat: Chococraft] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatExtraBiomes{1.6.4R2.7.9} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatForestry{1.6.4R2.7.9} [MFR Compat: Forestry] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatForestryPre{1.6.4R2.7.9} [MFR Compat: Forestry (part 2)] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatForgeMicroblock{1.6.4R2.7.9} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatIC2{1.6.4R2.7.9} [MFR Compat: IC2] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mystcraft{0.10.13.01} [Mystcraft] (mystcraft-uni-1.6.4-0.10.13.01.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatMystcraft{1.6.4R2.7.9} [MFR Compat: Mystcraft] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatPams{1.6.4R2.7.9} [MFR Compat: Pam's Mods] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatProjRed{1.6.4R2.7.9} [MFR Compat ProjectRed] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatRailcraft{1.6.4R2.7.9} [MFR Compat: Railcraft] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatRP2{1.6.4R2.7.9} [MFR Compat: RP2] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatSufficientBiomes{1.6.4R2.7.9} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatThaumcraft{1.6.4R2.7.9} [MFR Compat: Thaumcraft] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NetherOres{1.6.2R2.2.2} [Nether Ores] (NetherOres-2.2.2-55.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMultipart{1.0.0.244} [Forge Multipart] (ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion{3.0.0.7} [Thermal Expansion] (ThermalExpansion-3.0.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatThermalExpansion{1.6.4R2.7.9} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatTwilightForest{1.6.4R2.7.9} [MFR Compat: TwilightForest] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatVanilla{1.6.4R2.7.9} [MFR Compat: Vanilla] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatXyCraft{1.6.4R2.7.9} [MFR Compat: XyCraft] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Natura{2.1.14} [Natura] (Natura_mc1.6.X_2.1.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenMods{0.5} [OpenMods] (OpenModsLib-0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenBlocks{1.2.8} [OpenBlocks] (OpenBlocks-1.2.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenPeripheralCore{0.4} [OpenPeripheralCore] (OpenPeripheralCore-0.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    simplyjetpacks{0.3.0.0} [Simply Jetpacks] (SimplyJetpacks-0.3.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Statues{2.1.1} [Statues] (statues-1.6.4-2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.6.X_1.5.5.7} [Tinkers' Construct] (TConstruct_mc1.6.4_1.5.5.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TMechworks{33.c001660} [Tinkers' Mechworks] (TMechworks_mc1.6.4_0.1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    iChunUtil{2.4.0} [iChunUtil] (util^iChunUtil2.4.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WR-CBE|Core{1.4.0.7} [WR-CBE Core] (WR-CBE 1.4.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WR-CBE|Addons{1.4.0.7} [WR-CBE Addons] (WR-CBE 1.4.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WR-CBE|Logic{1.4.0.7} [WR-CBE Logic] (WR-CBE 1.4.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    McMultipart{1.0.0.244} [Minecraft Multipart Plugin] (ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMicroblock{1.0.0.244} [Forge Microblocks] (ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct Environment: Sane and ready for action. Bugs may be reported.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 171 (9576 bytes; 0 MB) allocated, 171 (9576 bytes; 0 MB) used
    Player Count: 0 / 20; []
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)
```

**Comment by jakimfett** [comment]
Thanks for reporting this. This problem was, unless I'm mistaken, addressed in the 5.0.5 bugfixes.

Please update to [Minechem 5.0.5-RC1 from CurseForge](http://minecraft.curseforge.com/mc-mods/73373-minechem-5/files) or [build #76 from the Minechem Jenkins](http://jenkins.jakimfett.com/build/job/Minechem/76/).

If your players use Particle Physics, please [read about the Minechem/Particle Physics split](http://jakimfett.com/status-report/splitting-minechem/) before making the jump to 5.0.5

The decomposition logic changed significantly in 5.0.5 ([you can read about the changes in @Maxwolf's PR](https://github.com/jakimfett/MineChem/pull/19)), and should resolve this.

Was it a vanilla repeater? Or a repeater from ChickenBones/ProjectRed/etc?

**Comment by birdwing** [comment]
It was a vanilla repeater.

I wasn't sure if 5.0.5-RC1 was stable enough for a server, which is why I hadn't upgraded. I will go ahead and try that now at your suggestion.

**Comment by Maxwolf** [comment]
5.0.5-RC1 is better for your server than what was before that much is for sure.

**Comment by jakimfett** [comment]
@birdwing in general, a release candidate means "This is stable enough for use on a live server, and if no bugs turn up in the next week or three, this will be the final $version release".

Unlike normal, 5.0.5 has been **entirely** bugfixes. So, with 5.0.5, later is always better. Make sure you read about the [Minechem/Particle Physics split](http://jakimfett.com/status-report/splitting-minechem/) before you upgrade though.

**Comment by jakimfett** [comment]
Given the lack of response from @birdwing and the fact that it's an outdated version of the mod with this problem, I'm closing this issue.
