### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by selriam** [AdlyTempleton/MineChem#231]
Time: 14.08.14 09:51
Description: Initializing game

java.lang.ArrayIndexOutOfBoundsException: 1
    at minechem.block.BlockSimple.func_149651_a(BlockSimple.java:210)
    at net.minecraft.client.renderer.texture.TextureMap.func_110573_f(TextureMap.java:432)
    at net.minecraft.client.renderer.texture.TextureMap.<init>(TextureMap.java:85)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at minechem.block.BlockSimple.func_149651_a(BlockSimple.java:210)
    at net.minecraft.client.renderer.texture.TextureMap.func_110573_f(TextureMap.java:432)
    at net.minecraft.client.renderer.texture.TextureMap.<init>(TextureMap.java:85)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by jakimfett** [comment]
Please provide all the information required by the [Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting). Without information, I can't help you.

**Comment by jakimfett** [comment]
Do NOT put your crash reports in the wiki. Read the bug reporting guidelines again, please.

**Comment by jakimfett** [comment]
No response, closing this ticket. Open a new ticket if you're still having this issue with Minechem 5.0.5-RC2
