### ISSUE TITLE
Minechem is REQUIRING forestry (with Biomes O Plenty?)

### ISSUE THREAD

**Issue by clubpetey** [AdlyTempleton/MineChem#35]
Fixed in promoted build #233

Installing Minechem with Biome-O-Plenty is also requiring forestry to be installed.  Trying to run MineChem/BOP alone generates a crash (below).  Removing Minechem allows everything to load fine.

This may be an issue with BoP, not sure, but then I would expect BoP to crash on it's own when Forestry is not installed.  

MineChem: 3.0.0-225
BoP: 0.5.5
Forge: 7.8.0.734
Forestry: 2.2.6.4
-pete

Crash report:

java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
    at com.google.common.base.Absent.get(Absent.java:42)
    at biomesoplenty.api.BlockReferences.getBlockItemStack(BlockReferences.java:205)
    at ljdp.minechem.common.recipe.MinechemRecipes.BOPExport(MinechemRecipes.java:45)
    at ljdp.minechem.common.recipe.MinechemRecipes.RegisterRecipes(MinechemRecipes.java:490)
    at ljdp.minechem.common.ModMinechem.preInit(ModMinechem.java:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:494)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)

**Comment by MFernflower** [comment]
try the newest build

**Comment by clubpetey** [comment]
Still broken with Release 228 :(

**Comment by clubpetey** [comment]
Sorry, forgot new stack trace:

java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
    at com.google.common.base.Absent.get(Absent.java:42)
    at biomesoplenty.api.BlockReferences.getBlockItemStack(BlockReferences.java:205)
    at ljdp.minechem.common.recipe.MinechemRecipes.RegisterRecipes(MinechemRecipes.java:480)
    at ljdp.minechem.common.ModMinechem.preInit(ModMinechem.java:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:494)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)

**Comment by Rushmead** [comment]
We Should be using the Ore Dict... Stupid Mandrake

**Comment by MFernflower** [comment]
I sent a fix in for this. Try http://bit.ly/11vNCGF

**Comment by clubpetey** [comment]
Uh, negative ghost rider, the pattern is full (still crashes):

java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
    at com.google.common.base.Absent.get(Absent.java:42)
    at biomesoplenty.api.BlockReferences.getBlockItemStack(BlockReferences.java:205)
    at ljdp.minechem.common.recipe.MinechemRecipes.RegisterRecipes(MinechemRecipes.java:479)
    at ljdp.minechem.common.ModMinechem.preInit(ModMinechem.java:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:494)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
.
.
.

**Comment by MFernflower** [comment]
Fixed in promoted build #233
